name: Check if service has codeowners

on:
  workflow_call:
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
jobs:
  check-has-codeowners:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: "Check file existence"
       id: is-codeowners-exist
       uses: andstor/file-existence-action@v1
       with:
        files: "CODEWONERS"
     - name: "Determine status"
       id: determine-status
       run: |
        if [ "${{ steps.is-codeowners-exist.outputs.files_exists }}" = "true" ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
        fi
     - name: "Update check run result"
       uses: port-labs/port-github-action@v1
       with:
         clientId: ${{ secrets.PORT_CLIENT_ID }}
         clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
         title: codeowners-${{ github.event.repository.name }}
         blueprint: CheckRun
         properties: |
           {
              "status": "${{ steps.determine-status.outputs.status }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "buildId": "${{ github.run_id }}"
           }
         relations: |
           {
             "service": "${{ github.event.repository.name }}",
             "check": "codeowners"
           } 
        