name: Check if service has fast api version that equals 0.85.2

on:
  workflow_call:
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
jobs:
  check-fastapi-version:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - name: "Check file contents"
       id: check-contents
       run: | 
        echo "::set-output name=fastapi-version::$(cat requirements.txt | grep fastapi)" 
     - name: "Determine status"
       id: determine-status
       run: |
        if [ "${{ steps.check-contents.outputs.fastapi-version }}" = "0.85.2" ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
        fi
     - name: "Update check run result"
       uses: port-labs/port-github-action@v1
       with:
         clientId: ${{ secrets.PORT_CLIENT_ID }}
         clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
         title: sentry-${{ github.event.repository.name }}
         blueprint: CheckRun
         properties: |
           {
              "status": "${{ steps.determine-status.outputs.status }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "buildId": "${{ github.run_id }}"
           }
         relations: |
           {
             "service": "${{ github.event.repository.name }}",
             "check": "fast-api-version"
           } 
        