name: Check if service has snyk vulnerabilities

on:
  workflow_call:
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
      SNYK_TOKEN: 
        required: true
jobs:
  check-has-snyk-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
     - run: pwd
     - run: ls -l
     - name: Run Snyk to check for vulnerabilities
       id: snyk
       continue-on-error: true
       uses: snyk/actions/python@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       with:
         args: --severity-threshold=high
     - name: "Determine status"
       id: determine-status
       run: |
        if [ "${{ steps.snyk.outcome }}" = "success" ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
        fi
     - name: "Update check run result"
       uses: port-labs/port-github-action@v1
       with:
         clientId: ${{ secrets.PORT_CLIENT_ID }}
         clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
         title: snyk-checkrun-${{ github.event.repository.name }}
         blueprint: CheckRun
         properties: |
           {
              "status": "${{ steps.determine-status.outputs.status }}"
           }
         relations: |
           {
             "service": "${{ github.event.repository.name }}",
             "check": "snyk-vulnerabilties"
           } 
        