name: Check if service has pager duty configure

on:
  workflow_call:
    secrets: 
      PORT_CLIENT_ID: 
        required: true
      PORT_CLIENT_SECRET: 
        required: true
      PAGER_DUTY_TOKEN: 
        required: true
jobs:
  pager:
    runs-on: ubuntu-latest
    steps:
     - run: |
          curl --request GET \
            --url 'https://api.pagerduty.com/services?include%5B%5D=teams' \
            --header 'Accept: application/vnd.pagerduty+json;version=2' \
            --header 'Authorization: Token token=${{ secrets.PAGER_DUTY_TOKEN }}' \
            --header 'Content-Type: application/json' -o pager.json
            
            echo ::set-output name=pager::$(cat pager.json | jq -c '.services[] | select(.name == "${{ github.event.repository.name }}")')
     - name: "Determine status"
       id: determine-status
       run: |
        echo ${{ steps.pager.outputs.pager }}
        if [ "${{ steps.pager.outputs.pager }}" = "success" ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
        fi
     - name: "Update check run result"
       uses: port-labs/port-github-action@v1
       with:
         clientId: ${{ secrets.PORT_CLIENT_ID }}
         clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
         title: snyk-checkrun-${{ github.event.repository.name }}
         blueprint: CheckRun
         properties: |
           {
              "status": "${{ steps.determine-status.outputs.status }}"
           }
         relations: |
           {
             "service": "${{ github.event.repository.name }}",
             "check": "snyk-vulnerabilties"
           } 
        