name: Run service maturity tests

on:
  workflow_dispatch:

jobs:
  check-has-readme:
    uses: ./.github/workflows/check-has-readme.yml
    secrets: 
      PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
      PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}