name: Run service maturity tests

on:
  workflow_dispatch:

jobs:
  check-has-readme:
    uses: ./.github/workflows/maturity-tests/check-has-readme.yml@main
  
  update-port-rank:
    needs: [check-has-readme]
    runs-on: ubuntu-latest
    steps: 
      - name: "Update port rank"
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          identifier: payment-service
          title: Payment Service
          blueprint: Service
          properties: |
            {
               "rank": "Bronze"
            }


